### ISSUE TITLE
Extend click area in dietpi-software.html

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Website#25]
Currently it's only possibly to extend the tiles by clicking exactly on '+' icon on https://dietpi.com/dietpi-software.html. The clicking area needs to be extended, making easier the access to the documentation,

**Comment by MichaIng** [comment]
I'm working on it. It required a CSS change: https://github.com/MichaIng/DietPi-Website/commit/092bec10321ebac0de9ecd46d292119818c8095d
Now this was possible: https://github.com/MichaIng/DietPi-Website/commit/2bc3d226a51269a69ce62cba0fd2efa0081e33cf

However I updated the CSS file and now we should wait a day before updating the HTML files, so that Cloudflare and browser caches have loaded the new CSS file, otherwise the HTML would break the tiles.

**Comment by fpetru** [comment]
It works quite nice. I mark this as resolved.
