### ISSUE TITLE
Reorganize DietPi-Website Headline and Slider

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Website#276]
### Headline

Goals:
- Remove lower important items (e.g. Testimonials)
- Emphasize Documentation, Blog, Donation

Idea: 
- Reorganize the headline with these items
  - Home
  - Features
  - Download
  - Documentation: Add (new: Linking of docs)
  - Forum: Add (new: Linking of docs)
  - Blog: Add (new: Linking of blogs)
  - Getting started: Remove (add as section below "Features" and above "Download"
  - Stats: Remove (is present as button „Truly Optimized“ below „Features“)
  - Donation: Add (new: Donation is a subsection of "Contribute" today, shall become an own section with own link)
  - Contribute
  - Testimonials: Remove

### Slider
Idea:
- Add Docs
- Add Forum
- Add Blog

@MichaIng @Joulinar @LOGIN-TB: 4discussion

**Comment by StephanStS** [comment]
@MichaIng: Open point is an extension of the slider with docs, forum, blog.

**Comment by MichaIng** [comment]
IMO there is no point to add docs/forum/blog to the slider when they are in the top navigation bar already. She should actually use the slider for more up-to-date information, like current blog posts, infos/topics etc. What you think?

The top navigation bar change and alignment across website, docs and blog makes very much sense.

Another idea. Probably we can add some "Read more" or "Learn more" text to the feature buttons, to better indicate that they are actually links.

We btw already replaced "Contribute" with "Donate". But you mean the section of the website, not the navigation bar? I guess this is rarely read by anyone, now that the navigation bar is not pointing to it anymore, so IMO we should not investigate much efforts in this section, keeping it small and simple. I would actually remove it completely, if that did not mean to invert coloring of the following sections, which is more work. But the same is true when splitting it into "Contribute" and "Donate", so that is even the less appealing change IMO.

"Getting started" is a section already, and IMO good where it is below downloads. But since docs, blog and forum will be own navigation buttons, it makes sense to remove it from the navigation bar, of course.
