### ISSUE TITLE
Personalize donate buttons

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Website#76]
Let's customize "Donate with PayPal" button:
- bringing the PayPal logo
- showing the donate cards

If we do for PayPal, we should also personalize the Patreon logo.

**Comment by Anulo2** [comment]
![image](https://github.com/MichaIng/DietPi-Website/assets/28984474/53211087-6a3d-4af1-b309-104ad412dfb2)

Something like this? What you mean with "showing the donate card"?

**Comment by Anulo2** [comment]
We could also customize the colors to match DietPi colors:

![image](https://github.com/MichaIng/DietPi-Website/assets/28984474/8f1cf7b4-eb79-4183-ac29-b75281523f56)

**Comment by Anulo2** [comment]
Should I do the pr with the customized logos or the original ones? @MichaIng

**Comment by MichaIng** [comment]
Many thanks for playing around with this. I personally like the green variant, but I still think it is better to stick with the original colors 😉. With "card" was meant the credit card logos below the PayPal button, to express that one can pay with credit cards through PayPal as well, no necessarily requiring a PayPal account. Like this one:

![](https://www.pngitem.com/pimgs/m/43-439830_paypal-png-download-image-credit-card-logos-with.png)

Probably we find SVGs of the individual credit card logos and can place them below the "Donate via PayPal" text, instead of using a combined PayPal+cards logo.

**Comment by Anulo2** [comment]
this issue should be closed @MichaIng
