### ISSUE TITLE
[website] add price to each board

### ISSUE THREAD

**Issue by mrx23dot** [MichaIng/DietPi-Website#93]
Please add price to each board at:

https://dietpi.com/survey/#benchmark

some price is still better than outdated price, just for a comparison. Or at least price range like $20-$30.

**Comment by MichaIng** [comment]
Many thanks for your suggestion, I moved it to the correct repository.

However, I believe adding SBC prices is nothing we can provide, as it depends on local vendors, tax etc and may be highly volatile in cases. We could use the prices listed on the manufacturers website, but that can be very different from what end users around the world finally have to pay and while I'd say "no price is still better than wrong price". Keeping it updated is additional burden, which at least I do not rate important or even helpful enough to shift time to, away from other tasks.

https://dietpi.com/survey/ is btw for survey data uploaded from our user that opted in, not for external info. But I probably see the intention of your suggestion to add it there, to have some sort of price-performance comparison. But note that synthetic benchmark values do not cover the value/performance of an SBC, where at least hardware features, support and build quality are other important aspects.

What I could think of is adding links to the manufacturers product page from our download section: https://dietpi.com/#download

**Comment by mrx23dot** [comment]
Even if we would have a hidden price we could sort them relative to each other, worst case some boards would swap places, but the ballpark would be ok. 

Use case: selecting the cheapest capable board for the job.

Yeah for #download site I meant.

Having a price API would be an overkill, easily broken with time.

**Comment by MichaIng** [comment]
> Even if we would have a hidden price we could sort them relative to each other

The SBC tiles mixer we use is generally able to take other HTML meta data and sort the tiles according to them, so technically it would be possible.

But it only makes sense when we had a way to reliably get and maintain correct prices. x86_64 systems would need to be taken out. And there are many SBCs which are available in several models (RPi, the modules are ages away from each others) or revisions or variable hardware features, especially different RAM sizes and optional WiFi modules. Also some come with heat pipe or fan and housing included, others not, same for PSU, which makes especially the cheaper SBCs hard to compare. Also in case of compatible bootloader and kernel+dtb, we have images that support multiple SBCs, like Nano Pi M4+NEO4+NanoPC T4, Odroid XU3+XU4+MC1+HC1+HC2 and Odroid C4+HC4, which have the same SoC but in cases very different other board features. This all makes it very difficult to get a meaningful price that can be used for such a comparison/rating.

> Use case: selecting the cheapest capable board for the job.

And as said, I think using only raw benchmark averages and a prices (even if it would be normalised for reasonable comparison) for buying decisions is simply wrong: There are many other aspects, as mentioned above, and also the way the benchmark value is taken is very synthetic and can never give a full picture or even show how fast it is for ones particular use case. E.g. you want to to video encoding, which is, when GPU drivers are available, a GPU feature, so that an extremely slow SoC with hardware-acceleration can do much better than a very new/fast SoC without. So really, if pure chip performance is such an important argument, then one needs to have a closer look at benchmarks for the dedicated task or type of task it will be used for.

Our benchmarks are there to give a rough overview, identify probably different CPU default clocks of SBCs with matching SoC, identify problems with the own hardware, that lead to a significant performance drop and to compare or review for pure interest. For a buying decision they should only play a minor role, IMO.

We could say: Who cares, a rough overview is better than none, but I'm not keen to publicly rate SBCs against each other without complete and strong comparison aspects. But that is not our job: We do not intensively test the performance of SBCs, but we test our OS on it, add hardware and software support. We had some kind of rating bars at our download page a while ago, but removed them purposefully, for the above mentioned reason.

**Comment by MichaIng** [comment]
Cleanup: I think this isn't reasonable and cannot be achieved. Best we can do and probably should is to add links to official wiki/docs and product pages of the manufacturer, where price info can be found, respectively links to actual distributors.
